name: Build

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

env:
  HUSKY: 0

jobs:
  build:
    name: Install package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6
        with:
          fetch-depth: 0

      - name: test
        run: |
          mkdir -p $HOME/.config/mise
          echo '[tools]
          node = "22"
          npm = "10"' > $HOME/.config/mise/config.toml
          cat $HOME/.config/mise/config.toml

      - name: Setup Node
        uses: jdx/mise-action@d16887ba50704baed7de72bd1e82e04391e4457a # v3
        with:
          cache: false

      - name: Controle node version
        run: |
          mise ls
          node --version
          npm --version

      - name: Check package-lock.json
        run: npm run package:check

      - name: Install package
        run: npm ci

      # https://commitlint.js.org/guides/ci-setup.html#github-actions
      - name: Validate PR commits with commitlint
        if: github.event_name == 'pull_request' && !startsWith(github.head_ref, 'copilot/')
        run: npx commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose --color

      - name: Run lint
        run: npm run prettier
